### ISSUE TITLE
Do you mind add some comments for code..?

### ISSUE THREAD

**Issue by e1001925** [bcopeland/wifi-crypto#4]
Dear bcopeland,

Ha here I am again. I am still struggling to implement SAE and I find this. But honestly I don't really understand some parts of the code like _serialize_number_.

I plan to follow your steps(since this code seems very clean) and write them in C with mbedtls. Could you please add some little comment? 

Best regards,
Michael

**Comment by bcopeland** [comment]
On Tue, May 15, 2018 at 11:51:02PM -0700, Michael65535 wrote:
> Dear bcopeland,
> 
> Ha here I am again. I am still struggling to implement SAE and I find this. But honestly I don't really understand some parts of the code like _serialize_number_.
> 
> I plan to follow your steps(since this code seems very clean) and write them in C with mbedtls. Could you please add some little comment? 
> 
> Best regards,
> Michael

I honestly think just adopting wpa_supplicant would be the path of
least resistance - if you'd started from there, you'd be done by now.

That said, to answer your questions:

 - serialize_number, if I recall correctly, takes a bignum and converts
   it to binary form.  It is implemented in the 'seccure' library:

https://github.com/bwesterb/py-seccure/blob/master/src/__init__.py#L57

 - to really understand SAE you should familiarize yourself with elliptic
   curve cryptography (e.g. read the wikipedia page) -- you don't have
   to know how to implement it but understanding the ECC point
   multiplication will help elucidate sae.py

 - after that, read the RFCs that SAE's inventor Dan Harkins has published,
   e.g.:
  - https://tools.ietf.org/html/rfc5931
  - https://tools.ietf.org/html/rfc6617

  If mbedtls supports ECC then having read those resources plus my sae.py
  should give enough background to understand the process.

 - there are two parts to mesh networks with SAE: one is the key exchange
   itself (all of the above), the other is the AMPE state machine.  For the
   latter, best resource is the 802.11 standard.  I think even authsae
   doesn't implement it perfectly.

-- 
Bob Copeland %% https://bobcopeland.com/
